apiVersion: apps/v1
kind: Deployment
metadata:
  name: aggregationdb
  namespace: onaimhub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aggregationdb
  template:
    metadata:
      labels:
        app: aggregationdb
    spec:
      containers:
        - name: aggregationdb
          image: postgres:13
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: aggregation
            - name: POSTGRES_PASSWORD
              value: Test1234!
            - name: POSTGRES_USER
              value: postgres

          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"

          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: aggregationdb
      restartPolicy: Always
      volumes:
        - name: aggregationdb
          persistentVolumeClaim:
            claimName: aggregationdb
