apiVersion: apps/v1
kind: Deployment
metadata:
  name: aggregation
  namespace: onaimhub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aggregation
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: aggregation
    spec:
      containers:
        - name: aggregation
          image: gvgroup/onaim-aggregationservice:latest
          ports:
            - containerPort: 8080
          env:
            - name: ConnectionStrings__Connection
              value: Host=postgres;Port=5432;Database=OnAimAggregation;Username=postgres;Password=Test1234!;Pooling=true;
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
          volumeMounts:
            - mountPath: /app/appsettings.json
              name: aggregation-cm0
              subPath: appsettings.json
      restartPolicy: Always
      imagePullSecrets:
        - name: dockerhub-secret
      volumes:
        - configMap:
            items:
              - key: appsettings.json
                path: appsettings.json
            name: aggregation-cm0
          name: aggregation-cm0
