apiVersion: v1
kind: Service
metadata:
  name: hubapidb
  namespace: onaimhub
spec:
  ports:
    - name: "5432"
      port: 5432
      targetPort: 5432
  selector:
    app: hubapidb
  type: ClusterIP



