apiVersion: apps/v1
kind: Deployment
metadata:
  name: hubapidb
  namespace: onaimhub
  labels:
    app: hubapidb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hubapidb
  template:
    metadata:
      labels:
        app: hubapidb
    spec:
      containers:
        - name: hubapidb
          image: postgres:13
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: OnAimHub
            - name: POSTGRES_PASSWORD
              value: '1234'
            - name: POSTGRES_USER
              value: postgres
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: hubapidb-data
      restartPolicy: Always
      volumes:
        - name: hubapidb-data
          persistentVolumeClaim:
            claimName: hubapidb-data
