stages:
  - build
  - test
  - tagged_latest
  - deploy

variables:
  DOCKER_IMAGE_TAG: $CI_COMMIT_REF_SLUG-$CI_PIPELINE_ID
  DOCKER_NAMESPACE: gvgroup
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""

services:
  - docker:dind


build_admin:
  image: docker
  stage: build
  script:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - echo "Building Admin API..."
    - docker build -t $DOCKER_NAMESPACE/onaim-admin_api:$DOCKER_IMAGE_TAG -f Admin/OnAim.Admin.API/Dockerfile .
    - docker push $DOCKER_NAMESPACE/onaim-admin_api:$DOCKER_IMAGE_TAG
  tags:
    - docker-runner

test_admin:
  stage: test
  script:
    - echo "Running tests for Admin API..."
  tags:
    - docker-runner
    
tagged_latest_admin:
  image: docker
  stage: tagged_latest
  script:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - echo "Pushing Admin API image to registry..."
    - docker pull $DOCKER_NAMESPACE/onaim-admin_api:$DOCKER_IMAGE_TAG
    - docker tag $DOCKER_NAMESPACE/onaim-admin_api:$DOCKER_IMAGE_TAG $DOCKER_NAMESPACE/onaim-admin_api:latest
    - docker push $DOCKER_NAMESPACE/onaim-admin_api:latest
  tags:
    - docker-runner
  only:
    - main
  needs:
    - build_admin


deploy_admin:
  stage: deploy
  image:
    name: bitnami/kubectl:latest
    entrypoint: ['']
  script:
    - echo "Deploying Admin API..."
    - kubectl config use-context onaim/onaimback/k8s-connection:k8s-connection
    - sed -i "s|gvgroup/onaim-admin_api:latest|gvgroup/onaim-admin_api:$DOCKER_IMAGE_TAG|g" Admin/adminapi-k8s/adminapi-deployment.yaml
    - kubectl apply -f Admin/adminapi-k8s/adminapi-deployment.yaml -f Admin/adminapi-k8s/adminapi-service.yaml -f Admin/adminapi-k8s/adminapi-ingress.yaml -f Admin/adminapi-k8s/adminapi-cm0-configmap.yaml -f Admin/adminapi-k8s/secret.yaml
  tags:
    - docker-runner
  only:
    - main
  when: manual  
 

 