stages:
  - build
  - test
  - push
  - deploy

variables:
  DOCKER_IMAGE_TAG: $CI_COMMIT_SHA
  DOCKER_NAMESPACE: gvgroup
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""

services:
  - docker:dind

before_script:
  - apk add --no-cache docker-cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin



build_admin:
  stage: build
  script:
    - echo "Building Admin API..."
    - docker build -t $DOCKER_NAMESPACE/onaimhub-admin_api:$DOCKER_IMAGE_TAG -f Admin/OnAim.Admin.API/Dockerfile .
    - docker push $DOCKER_NAMESPACE/onaimhub-admin_api:$DOCKER_IMAGE_TAG
  tags:
    - docker-runner

# test_admin:
#   stage: test
#   script:
#     - echo "Running tests for Admin API..."
#   tags:
#     - docker-runner
    
push_admin:
  stage: push
  script:
    - echo "Pushing Admin API image to registry..."
    - docker pull $DOCKER_NAMESPACE/onaimhub-admin_api:$DOCKER_IMAGE_TAG
    - docker tag $DOCKER_NAMESPACE/onaimhub-admin_api:$DOCKER_IMAGE_TAG $DOCKER_NAMESPACE/onaimhub-admin_api:latest
    - docker push $DOCKER_NAMESPACE/onaimhub-admin_api:latest
  tags:
    - docker-runner
  only:
    - main
  needs:
    - build_admin

deploy_admin:
  stage: deploy
  image:
    name: bitnami/kubectl:latest
    entrypoint: ['']
  script:
    - echo "Deploying Admin API..."
    - kubectl config use-context onaim/onaimback/k8s-connection:k8s-connection
    - kubectl apply -f Admin/OnAim.Admin.API/k8s/*.yaml
  tags:
    - docker-runner
  only:
    - main
  when: manual  
 

 