apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: leveldb-data
  name: leveldb-data
  namespace: onaimhub
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
  storageClassName: local-path
