version: '3.9'

services:
  rabbitmq:
    image: docker.io/masstransit/rabbitmq:latest
    container_name: "rabbitmq"
    deploy:
      mode: replicated
      replicas: 1
    ports:
      - "5672:5672"
      - "15672:15672"
  
  consul:
    image: consul:1.7.14
    ports:
      - "8500:8500"
    command: "consul agent -dev -client=0.0.0.0"

  ocelotapigateway:
    build:
      context: .
      dockerfile: ApiGateway/Dockerfile
    ports:
      - "5000:8080"  # Map host port 5000 to container port 8080
    depends_on:
      - consul
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - CONSUL_ADDRESS=http://consul:8500
    volumes:
      - ./ApiGateway/appsettings.json:/app/appsettings.json
      - ./ApiGateway/ocelot.json:/app/ocelot.json

  wheelapi:
    build:
      context: .
      dockerfile: Wheel/Wheel.Api/Dockerfile
    ports:
      - "5001:8080"  # Map host port 5001 to container port 8080
    depends_on:
      - consul
      - gameconfigdb
      - gamehistorydb
    environment:
      - CONSUL_ADDRESS=http://consul:8500
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__GameConfig=Host=gameconfigdb;Port=5432;Database=WheelConfig;Username=postgres;Password=Test1234!
      - ConnectionStrings__GameHistory=Host=gamehistorydb;Port=5432;Database=WheelHistory;Username=postgres;Password=Test1234!
    volumes:
      - ./Wheel/Wheel.Api/appsettings.json:/app/appsettings.json
      
  hubapi:
    build:
      context: .
      dockerfile: Hub/Hub.Api/Dockerfile
    ports:
      - "5002:8080"  # Map host port 5002 to container port 8080
    depends_on:
      - consul
    environment:
      - CONSUL_ADDRESS=http://consul:8500
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ./Hub/Hub.Api/appsettings.json:/app/appsettings.json
      
  gameconfigdb:
    image: postgres:13
    environment:
      POSTGRES_DB: WheelConfig
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Test1234!
    ports:
      - "5432:5432"
    volumes:
      - gameconfigdb_data:/var/lib/postgresql/data

  gamehistorydb:
    image: postgres:13
    environment:
      POSTGRES_DB: WheelHistory
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Test1234!
    ports:
      - "5433:5432"
    volumes:
      - gamehistorydb_data:/var/lib/postgresql/data

volumes:
  gameconfigdb_data:
  gamehistorydb_data: