version: '3.9'
 
services: 
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: ["redis-server", "--appendonly", "yes"]

  mongo:
    image: mongo:latest
    restart: always
    container_name: mongo
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db
  
  rabbitmq:
    container_name: rabbitmq
    image: docker.io/masstransit/rabbitmq:latest
    restart: unless-stopped
    deploy:
      mode: replicated
      replicas: 1
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq:/var/lib/rabbitmq/mnesia/

  consul:
    image: consul:1.7.14
    ports:
      - "8500:8500"
    command: "consul agent -dev -client=0.0.0.0"
 
  ocelotapigateway:
    extends:
       file: ./ApiGateways/ApiGateway/compose.yml
       service: ocelotapigateway
 
  wheelapi:
     extends:
      file: ./Games/Wheel/Wheel.Api/compose.yml
      service: wheelapi

  penaltykicksapi:
     extends:
      file: ./Games/PenaltyKicks/PenaltyKicks.Api/compose.yml
      service: penaltykicksapi

  hubapi:
      extends:
        file: ./Core/Hub/Hub.Api/compose.yml
        service: hubapi
 
  adminapi:
      extends:
         file: ./Admin/OnAim.Admin.API/compose.yml
         service: adminapi

  # aggregation:
  #     extends: 
  #        file: ./Docker/aggregation/compose.yml
  #        service: aggregation
 
  levelapi:
     extends:
        file: ./CoreModules/LevelService/LevelService.Api/compose.yml
        service: levelapi

  missionapi:
     extends:
        file: ./CoreModules/MissionService/MissionService.Api/compose.yml
        service: missionapi

  leaderboardapi:
     extends:
        file: ./CoreModules/Leaderboard/Leaderboard.Api/compose.yml
        service: leaderboardapi

  testapi:
     extends:
        file: ./Helpers/Test.Api/compose.yml
        service: testapi
 
  admindb:
    image: postgres:13
    container_name: admindb
    restart: always
    environment:
      POSTGRES_DB: OnAimAdmin
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Test1234!
    ports:
      - "5432:5432"
    volumes:
      - admindb_data:/var/lib/postgresql/data

  hubdb:
    image: postgres:13
    container_name: hubdb
    restart: always
    environment:
      POSTGRES_DB: OnAimHub
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Test1234!
    expose:
      - "5433"
    ports:
      - "5433:5432"
    volumes:
      - hubdb_data:/var/lib/postgresql/data
    command: -p 5433

  gameconfigdb:
    image: postgres:13
    environment:
      POSTGRES_DB: WheelConfig
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Test1234!
    expose:
        - "5434"
    ports:
      - "5434:5432"
    volumes:
      - gameconfigdb_data:/var/lib/postgresql/data
    command: -p 5434  
  
  gamehistorydb:
    image: postgres:13
    environment:
      POSTGRES_DB: WheelHistory
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Test1234!
    expose:
        - "5435"
    ports:
      - "5435:5432"
    volumes:
      - gamehistorydb_data:/var/lib/postgresql/data
    command: -p 5435  

  penaltyconfigdb:
    image: postgres:13
    environment:
      POSTGRES_DB: PenaltyConfig
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Test1234!
    expose:
        - "5445"
    ports:
      - "5445:5432"
    volumes:
      - penaltyconfigdb_data:/var/lib/postgresql/data
    command: -p 5445  

  leveldb:
    image: postgres:13
    environment:
      POSTGRES_DB: OnAimLevel
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Test1234!
    expose:
        - "5436"
    ports:
      - "5436:5432"
    volumes:
      - leveldb_data:/var/lib/postgresql/data
    command: -p 5436

  missiondb:
    image: postgres:13
    environment:
      POSTGRES_DB: OnAimMission
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Test1234!
    expose:
        - "5437"
    ports:
      - "5437:5432"
    volumes:
      - missiondb_data:/var/lib/postgresql/data
    command: -p 5437

  leaderboarddb:
    image: postgres:13
    environment:
      POSTGRES_DB: OnAimLeaderboard
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Test1234!
    expose:
        - "5438"
    ports:
      - "5438:5432"
    volumes:
      - leaderboarddb_data:/var/lib/postgresql/data
    command: -p 5438

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
 
volumes:
  admindb_data:
    driver: local
  hubdb_data:
    driver: local
  gameconfigdb_data:
    driver: local
  gamehistorydb_data:
    driver: local
  leveldb_data:
    driver: local
  missiondb_data:
    driver: local
  leaderboarddb_data:
    driver: local
  mongo-data:
    driver: local
  redis_data:
    driver: local
  rabbitmq:
    driver: local
  penaltyconfigdb_data:
    driver: local
  pgadmin_data:
    driver: local
  consul_data:
    driver: local

 # postgres:
 #    image: postgres:13
 #    container_name: postgres
 #    restart: always
 #    environment:
 #      POSTGRES_USER: postgres
 #      POSTGRES_PASSWORD: Test1234!
 #    ports:
 #      - "5432:5432"
 #    volumes:
 #      - postgres_data:/var/lib/postgresql/data
 #    command: >
 #      bash -c "
 #        # Create databases on container startup
 #        docker-entrypoint.sh postgres & 
 #        until pg_isready -h localhost -p 5432; do
 #          echo 'Waiting for PostgreSQL to start...';
 #          sleep 2;
 #        done;
 #        psql -U postgres -c 'CREATE DATABASE OnAimAdmin;';
 #        psql -U postgres -c 'CREATE DATABASE OnAimHub;';
 #        psql -U postgres -c 'CREATE DATABASE WheelConfig;';
 #        psql -U postgres -c 'CREATE DATABASE WheelHistory;';
 #        psql -U postgres -c 'CREATE DATABASE OnAimLevel;';
 #        psql -U postgres -c 'CREATE DATABASE OnAimMission;';
 #        psql -U postgres -c 'CREATE DATABASE OnAimLeaderboard;';
 #        wait
 #      "