version: '3.9'

services:
  rabbitmq:
    image: docker.io/masstransit/rabbitmq:latest
    container_name: "rabbitmq"
    deploy:
      mode: replicated
      replicas: 1
    ports:
      - "5672:5672"
      - "15672:15672"
  
  consul:
    image: consul:1.7.14
    ports:
      - "8500:8500"
    command: "consul agent -dev -client=0.0.0.0"

  ocelotapigateway:
    build:
      context: .
      dockerfile: ApiGateway/Dockerfile
    ports:
      - "5000:8080"  # Map host port 5000 to container port 8080
    depends_on:
      - consul
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - CONSUL_ADDRESS=http://consul:8500
    volumes:
      - ./ApiGateway/appsettings.json:/app/appsettings.json
      - ./ApiGateway/ocelot.json:/app/ocelot.json

  wheelapi:
    build:
      context: .
      dockerfile: Games/Wheel/Wheel.Api/Dockerfile
    ports:
      - "5001:8080"  # Map host port 5001 to container port 8080
    depends_on:
      - consul
      - gameconfigdb
      - gamehistorydb
    environment:
      - CONSUL_ADDRESS=http://consul:8500
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__GameConfig=Host=gameconfigdb;Port=5432;Database=WheelConfig;Username=postgres;Password=1234
      - ConnectionStrings__GameHistory=Host=gamehistorydb;Port=5432;Database=WheelHistory;Username=postgres;Password=1234
    volumes:
      - ./Games/Wheel/Wheel.Api/appsettings.json:/app/appsettings.json
       
  hubapi:
    build:
      context: .
      dockerfile: Hub/Hub.Api/Dockerfile
    ports:
      - "5002:8080"  # Map host port 5002 to container port 8080
    depends_on:
      - consul
    environment:
      - CONSUL_ADDRESS=http://consul:8500
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ./Hub/Hub.Api/appsettings.json:/app/appsettings.json

  adminapi:
    build:
      context: .
      dockerfile: Admin/OnAim.Admin.API/Dockerfile
    ports:
      - "5003:8080"
    depends_on:
      - mongodb
    environment:
      - CONSUL_ADDRESS=http://consul:8500
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ./Admin/OnAim.Admin.Api/appsettings.json:/app/appsettings.json

  gameconfigdb:
    image: postgres:13
    environment:
      POSTGRES_DB: WheelConfig
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - gameconfigdb_data:/var/lib/postgresql/data

  gamehistorydb:
    image: postgres:13
    environment:
      POSTGRES_DB: WheelHistory
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5433:5432"
    volumes:
      - gamehistorydb_data:/var/lib/postgresql/data

  admin.database:
    image: postgres:latest
    container_name: admin_database
    environment:
      POSTGRES_DB: admin
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
    volumes:
      - admin_database_data:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    networks:
      - backend

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - backend

volumes:
  gameconfigdb_data:
    driver: local
  gamehistorydb_data:
    driver: local
  admin_database_data:
    driver: local
  mongo_data:
    driver: local

networks:
  backend:
    driver: bridge
