version: '3.8'

services:
  penaltykicksapi:
    build:
      context: ../../../
      dockerfile: Games/PenaltyKicks/PenaltyKicks.Api/Dockerfile
    ports:
      - "5011:8080"
    depends_on:
      - consul
      - penaltyconfigdb
      # - gamehistorydb
    environment:
      - CONSUL_ADDRESS=http://consul:8500
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - ConnectionStrings__GameConfig=Host=penaltyconfigdb;Port=5445;Database=PenaltyConfig;Username=postgres;Password=Test1234!
      # - ConnectionStrings__GameHistory=Host=gamehistorydb;Port=5435;Database=WheelHistory;Username=postgres;Password=Test1234!
    volumes:
      - ./appsettings.json:/app/appsettings.json
    command: ["dotnet", "ef", "database update"]

volumes:
  penaltyconfigdb_data:
#   gamehistorydb_data:  