version: '3.8'

services:
  penaltykicksapi:
    build:
      context: ../../../
      dockerfile: Games/PenaltyKicks/PenaltyKicks.Api/Dockerfile
    ports:
      - "5011:8080"
    depends_on:
      - consul
      - postgres
    environment:
      - CONSUL_ADDRESS=http://consul:8500
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - ConnectionStrings__GameConfig=Host=postgres;Port=5432;Database=PenaltyConfig;Username=postgres;Password=Test1234!
      - ConnectionStrings__GameHistory=Host=postgres;Port=5432;Database=PenaltyHistory;Username=postgres;Password=Test1234!
    volumes:
      - ./appsettings.json:/app/appsettings.json
    command: ["dotnet", "ef", "database update"] 