stages:
  - build
  - test
  - tagged_latest
  - deploy
variables:
  DOCKER_IMAGE_TAG: $CI_COMMIT_SHA
  DOCKER_NAMESPACE: gvgroup
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""

services:
  - docker:dind

before_script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

build_Leaderboard:
  stage: build
  script:
    - echo "Building  LeaderBorad.."
    - docker build -t $DOCKER_NAMESPACE/onaim-leaderboard:$DOCKER_IMAGE_TAG -f CoreModules/Leaderboard/Leaderboard.Api/Dockerfile .
    - echo "Pushing Docker image for onaim-leaderboard to Docker Hub..."
    - docker push $DOCKER_NAMESPACE/onaim-leaderboard:$DOCKER_IMAGE_TAG
  tags:
    - docker-runner

# test_Leaderboard:
#   stage: test
#   script:
#     - echo "Running tests for LeaderBorad...."
#   tags:
#     - docker-runner

tagged_latest_Leaderboard:
  stage: tagged_latest
  script:
    - echo "Pushing LeaderBorad...."
    - docker pull $DOCKER_NAMESPACE/onaim-leaderboard:$DOCKER_IMAGE_TAG
    - docker tag $DOCKER_NAMESPACE/onaim-leaderboard:$DOCKER_IMAGE_TAG $DOCKER_NAMESPACE/onaim-leaderboard:latest
    - docker push $DOCKER_NAMESPACE/onaim-leaderboard:latest
  tags:
    - docker-runner
  only:
    - main
  needs:
    - build_Leaderboard
  when: manual

deploy_Leaderboard:
  stage: deploy
  script:
    - echo "Deploying LeaderBorad...."
    - kubectl config use-context onaim/onaimback/k8s-connection:k8s-connection
    - kubectl apply -f CoreModules/Leaderboard/leaderboardapi-k8s/leaderboardapi-deployment.yaml -f CoreModules/Leaderboard/leaderboardapi-k8s/leaderboardapi-service.yaml -f CoreModules/Leaderboard/leaderboardapi-k8s/leaderboardapi-ingress.yaml -f CoreModules/Leaderboard/leaderboardapi-k8s/leaderboardapi-cm0-configmap.yaml -f CoreModules/Leaderboard/leaderboardapi-k8s/secret.yaml
  only:
    - main
  when: manual
  tags:
    - docker-runner