stages:
  - build
  - test
  - push
  - deploy


variables:
  DOCKER_IMAGE_TAG: $CI_COMMIT_SHA
  DOCKER_NAMESPACE: gvgroup
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""

services:
  - docker:dind

before_script:
  - apk add --no-cache docker-cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

build_Wheel:
  stage: build
  script:
    - echo "Building Wheel"
    # - docker build -t $DOCKER_NAMESPACE/onaimhub-wheel:$DOCKER_IMAGE_TAG 
    # - echo "Pushing Docker image for onaimhub-wheel to Docker Hub..."
    # - docker push $DOCKER_NAMESPACE/onaimhub-wheel:$DOCKER_IMAGE_TAG
  tags:
    - docker-runner

# test_Wheel:
#   stage: test
#   script:
#     - echo "Running tests for Wheel""
#   tags:
#     - docker-runner

push_Wheel:
  stage: push
  script:
    - echo "Pushing Wheel""
    # - docker pull $DOCKER_NAMESPACE/onaimhub-wheel:$DOCKER_IMAGE_TAG
    # - docker tag $DOCKER_NAMESPACE/onaimhub-wheel:$DOCKER_IMAGE_TAG $DOCKER_NAMESPACE/onaimhub-wheel:latest
    # - docker push $DOCKER_NAMESPACE/onaimhub-wheel:latest
  tags:
    - docker-runner
  only:
    - main
  needs:
    - build_Wheel

deploy_Wheel:
  stage: deploy
  script:
    - echo "Deploying Wheel""
    - kubectl config use-context onaim/onaimback/k8s-connection:k8s-connection
    - kubectl apply -f Games/Wheel/wheelapi/k8s/*.yaml
  only:
    - main
  when: manual
  tags:
    - docker-runner