version: '3.8'

services:
  wheelapi:
    build:
      context: ../../../
      dockerfile: Games/Wheel/Wheel.Api/Dockerfile
    ports:
      - "5001:8080"
    depends_on:
      - consul
      - gameconfigdb
      - gamehistorydb
    environment:
      - CONSUL_ADDRESS=http://consul:8500
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__GameConfig=Host=gameconfigdb;Port=5434;Database=WheelConfig;Username=postgres;Password=Test1234!
      - ConnectionStrings__GameHistory=Host=gamehistorydb;Port=5435;Database=WheelHistory;Username=postgres;Password=Test1234!
    volumes:
      - ./appsettings.json:/app/appsettings.json
    command: ["dotnet", "ef", "database update"]

volumes:
  gameconfigdb_data:
  gamehistorydb_data:  