apiVersion: v1
kind: Service
metadata:
  name: consul
  namespace: onaimhub
  labels:
    app: consul
spec:
  ports:
    - name: "8500"
      port: 8500
      targetPort: 8500
  selector:
    app: consul
  type: ClusterIP  # Use NodePort or LoadBalancer if external access is required

