apiVersion: apps/v1
kind: Deployment
metadata:
  name: consul
  namespace: onaimhub
  labels:
    app: consul
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consul
  template:
    metadata:
      labels:
        app: consul
    spec:
      containers:
        - name: consul
          image: consul:1.7.14
          ports:
            - containerPort: 8500
          command:
            - consul
            - agent
            - -dev
            - -client=0.0.0.0
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"



# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: consul
#   namespace: consul
#   labels:
#     app: consul
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: consul
#   template:
#     metadata:
#       labels:
#         app: consul
#     spec:
#       containers:
#         - name: consul
#           image: consul:1.7.14
#           args:
#             - consul
#             - agent
#             - -dev
#             - -client=0.0.0.0
#           ports:
#             - containerPort: 8500
#               protocol: TCP
#           resources:
#             requests:
#               memory: "256Mi"
#               cpu: "250m"
#             limits:
#               memory: "512Mi"
#               cpu: "500m"
#       restartPolicy: Always
