apiVersion: v1
kind: Service
metadata:
  name: sagamachine
  namespace: onaimhub
spec:
  ports:
    - name: "5007"
      port: 5007
      targetPort: 8080
  selector:
    app: sagamachine
  type: ClusterIP

