apiVersion: v1
kind: Service
metadata:
  name: wheelapi
  namespace: onaimhub
spec:
  ports:
    - name: http
      port: 5001
      targetPort: 8080
  selector:
    app: wheelapi
  type: ClusterIP


