apiVersion: apps/v1
kind: Deployment
metadata:
  name: gameconfigdb
  namespace: onaimhub
  labels:
    app: gameconfigdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gameconfigdb
  template:
    metadata:
      labels:
        app: gameconfigdb
    spec:
      containers:
        - name: gameconfigdb
          image: postgres:13
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: WheelConfig
            - name: POSTGRES_PASSWORD
              value: Test1234!
            - name: POSTGRES_USER
              value: postgres
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: gameconfigdb-data
      restartPolicy: Always
      volumes:
        - name: gameconfigdb-data
          persistentVolumeClaim:
            claimName: gameconfigdb-data
