apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: aggregationdb
  namespace: onaimhub
  labels:
    app: aggregationdb
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
  storageClassName: local-path

