apiVersion: apps/v1
kind: Deployment
metadata:
  name: admindb
  namespace: onaimhub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admindb
  template:
    metadata:
      labels:
        app: admindb
    spec:
      containers:
        - name: admindb
          image: postgres:13
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: OnAimAdmin
            - name: POSTGRES_PASSWORD
              value: Test1234!
            - name: POSTGRES_USER
              value: postgres

          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: admindb