stages:
  - build
  - test
  - tagged_latest
  - deploy

variables:
  DOCKER_IMAGE_TAG: $CI_COMMIT_SHA
  DOCKER_NAMESPACE: gvgroup
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""

services:
  - docker:dind

before_script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

build_ApiGateway:
  stage: build
  script:
    - echo "Building  API GAT..."
    - docker build -t $DOCKER_NAMESPACE/onaim-apigateway:$DOCKER_IMAGE_TAG -f ApiGateways/ApiGateway/Dockerfile .
    - echo "Pushing Docker image for onaim-apigateway to Docker Hub..."
    - docker push $DOCKER_NAMESPACE/onaim-apigateway:$DOCKER_IMAGE_TAG
  tags:
    - docker-runner

# test_ApiGateway:
#   stage: test
#   script:
#     - echo "Running tests for API GAT..."
#   tags:
#     - docker-runner
    
tagged_latest_ApiGateway:
  stage: tagged_latest
  script:
    - echo "Pushing API GAT..."
    - docker pull $DOCKER_NAMESPACE/onaim-apigateway:$DOCKER_IMAGE_TAG
    - docker tag $DOCKER_NAMESPACE/onaim-apigateway:$DOCKER_IMAGE_TAG $DOCKER_NAMESPACE/onaim-apigateway:latest
    - docker push $DOCKER_NAMESPACE/onaim-apigateway:latest
  tags:
    - docker-runner
  only:
    - main
  needs:
    - build_ApiGateway
  when: manual
    
deploy_ApiGateway:
  stage: deploy
  script:
    - echo "Deploying API GAT..."
    - kubectl config use-context onaim/onaimback/k8s-connection:k8s-connection
    - kubectl apply -f ApiGateways/ApiGateway/ocelotapigateway-k8s/ocelotapigateway-deployment.yaml -f ApiGateways/ApiGateway/ocelotapigateway-k8s/ocelotapigateway-service.yaml -f ApiGateways/ApiGateway/ocelotapigateway-k8s/ocelotapigateway-ingress.yaml -f ApiGateways/ApiGateway/ocelotapigateway-k8s/ocelotapigateway-cm0-configmap.yaml -f ApiGateways/ApiGateway/ocelotapigateway-k8s/ocelotapigateway-cm1-configmap.yaml -f ApiGateways/ApiGateway/ocelotapigateway-k8s/secret.yaml
  only:
    - main
  when: manual
  tags:
    - docker-runner
 

