apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gamehistorydb-data
  onaimhub: onaimhub
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
  storageClassName: local-path
  
