apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: missiondb-data
  namespace: onaimhub
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
  storageClassName: local-path
