version: '3.8'

services:
  hubapi:
    build:
      context: ../../../
      dockerfile: Core/Hub/Hub.Api/Dockerfile
    ports:
      - '5002:8080'
    depends_on:
      - postgres
      - consul
    environment:
      - CONSUL_ADDRESS=http://consul:8500
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Connection=Host=postgres;Port=5432;Database=OnAimHub;Username=postgres;Password=Test1234!;Pooling=true;
    volumes:
      - ./appsettings.json:/app/appsettings.json
    command: ["dotnet", "ef", "database update"]