stages:
  - build
  - test
  - push
  - deploy

variables:
  DOCKER_IMAGE_TAG: $CI_COMMIT_SHA
  DOCKER_NAMESPACE: gvgroup
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""

services:
  - docker:dind

before_script:
  - apk add --no-cache docker-cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker info


build_MissionService:
  stage: build
  script:
    - echo "Building  MissionService"
    # - docker build -t $DOCKER_NAMESPACE/onaimhub-missionservice:$DOCKER_IMAGE_TAG -f CoreModules/MissionService/MissionService.Api/Dockerfile .
    # - echo "Pushing Docker image for onaimhub-missionservice to Docker Hub..."
    # - docker push $DOCKER_NAMESPACE/onaimhub-missionservice:$DOCKER_IMAGE_TAG
  tags:
    - docker-runner

# test_MissionService:
#   stage: test
#   script:
#     - echo "Running tests for MissionService"
#   tags:
#     - docker-runner

push_MissionService:
  stage: push
  script:
    - echo "Pushing MissionService"
    # - docker pull $DOCKER_NAMESPACE/onaimhub-missionservice:$DOCKER_IMAGE_TAG
    # - docker tag $DOCKER_NAMESPACE/onaimhub-missionservice:$DOCKER_IMAGE_TAG $DOCKER_NAMESPACE/onaimhub-missionservice:latest
    # - docker push $DOCKER_NAMESPACE/onaimhub-missionservice:latest
  tags:
    - docker-runner
  only:
    - main
  needs:
    - build_MissionService

deploy_MissionService:
  stage: deploy
  script:
    - echo "Deploying MissionService to Kubernetes"
    - kubectl config use-context onaim/onaimback/k8s-connection:k8s-connection
    - kubectl apply -f CoreModules/MissionService/missionapi/k8s/*.yaml
  only:
    - main
  when: manual
  tags:
    - docker-runner