# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: level-config
#   namespace: level
# data:
#   appsettings.json: |
#     {
#       "Logging": {
#         "LogLevel": {
#           "Default": "Information",
#           "Microsoft.AspNetCore": "Warning"
#         }
#       },
#       "AllowedHosts": "*"
#     }


apiVersion: v1
data:
  appsettings.json: |-
    {
      "Logging": {
        "LogLevel": {
          "Default": "Information",
          "Microsoft.AspNetCore": "Warning"
        }
      },
      "ConnectionStrings": {
        "OnAimLevel": "User ID=postgres;Password=Test1234!;Host=leveldb;Port=5432;Database=OnAimLevel;Pooling=true;" //Akaki
      },
      "JwtConfiguration": {
        "PublicKey": "MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEhRGzVPGyq8lyFY/6xgdZiQT06c5k6RLauQjuE8zk6iXNP1EX86xZ8iQ4K/pB4Pw6u4b3stAxwnbwyOYPBngVUA==",
        "Issuer": "HUB",
        "Audience": "HUB-AUDIENCE"
      },
      "RabbitMQSettings": {
        "Host": "rabbitmq",
        "Port": "5672",
        "User": "guest",
        "Password": "guest",
        "ExchangeName": "levels.fanout",
        "Queues": {
          "UpdatePlayerExperienceQueue": {
            "QueueName": "UpdatePlayerExperienceQueue",
            "RoutingKeys": [ "levels_updatePlayerExperienceEvent" ]
          }
        },
        "Consumers": {
          "UpdatePlayerExperienceAggregationConsumer": {
            "UpdatePlayerExperienceEvent": "levels_updatePlayerExperienceEvent"
          }
        }
      },
      "AllowedHosts": "*"
    }
kind: ConfigMap
metadata:
  annotations:
    use-subpath: "true"
  labels:
    io.kompose.service: levelapi
  name: levelapi-cm0
  namespace: onaimhub