apiVersion: v1
data:
  appsettings.json: |
    {
      "ConnectionStrings": {
        "DefaultConnectionString": "Host=admindb;Port=5435;Database=OnAimAdmin;Username=postgres;Password=Test1234!;Pooling=true;",
        "HubDefaultConnectionString": "User ID=postgres;Password=1234;Server=hubdb;Port=5432;Database=OnAimHub;Pooling=true;",
        "LeaderBoardDefaultConnectionString": "User ID=postgres;Password=Test1234!;Server=leaderboarddb;Port=5432;Database=OnAimLeaderboard;Pooling=true;"

        # "DefaultConnectionString": "Host=192.168.10.42;Port=5432;Database=Publish;Username=postgres;Password=12345678",
        # "HubDefaultConnectionString": "User ID =postgres;Password=1234;Server=192.168.10.49;Port=5432;Database=OnAimHub;Pooling=true;",
        # "LeaderBoardDefaultConnectionString": "User ID =postgres;Password=Test1234!;Server=192.168.10.46;Port=5432;Database=OnAimLeaderboard;Pooling=true;"
      },
      "MongoDB": {
        "Connection": "mongodb://mongo::27017/",
        "DatabaseName": "AdminMongoDb"
      },
      "PromotionViewConfiguration": {
        "Host": "file://192.168.88.180/onAim/Avto",
        "Directory": "promotion-views",
        "TemplateDirectory": "promotion-views/templates"
      },
      "RabbitMQSettings": {
        "ConnectionName": "admin-service",
        "Retries": 3,
        "RetryInterval": 2,
        "ConventionsCasing": "snakeCase",
        "Host": "rabbitmq",
        "Port": "5672",
        "User": "guest",
        "Password": "guest",
        "RequestedConnectionTimeout": "00:00:30",
        "RequestedHeartbeat": "00:01:00",
        "SocketReadTimeout": "00:00:30",
        "SocketWriteTimeout": "00:00:30",
        "ContinuationTimeout": "00:00:20",
        "HandshakeContinuationTimeout": "00:00:10",
        "NetworkRecoveryInterval": "00:00:05",
        "Exchange": {
          "declare": true,
          "durable": true,
          "autoDelete": false,
          "type": "topic",
          "name": "deliveries"
        },
        "Queue": {
          "declare": true,
          "durable": true,
          "exclusive": false,
          "autoDelete": false,
          "template": "{{assembly}}/{{exchange}}.{{message}}"
        },
        "context": {
          "enabled": true,
          "header": "message_context"
        },
        "spanContextHeader": "span_context",
        "deadLetter": {
          "enabled": true,
          "prefix": "dlx-",
          "declare": true
        }
      },
      "JwtConfiguration": {
        "Issuer": "onaim-admin-api",
        "Audience": "*",
        "Secret": "BNyel3peNNZEhzFJo1fKCesZWzvbMceaB1TyOhhZSvr8xUeoklTHTARhCEtebPJjO96FXpCSxPtjiHlKV5l0OmX5KlVqnuGQgbLsBNyel3peNNZEhzFJo1fKCesZWzvbMceaB1TyOhhZSvr8xUeoklTHTARhCEtebPJjO96FXpCSxPtjiHlKV5l0OmX5KlVqnuGQgbLs"
      },
      "Serilog": {
        "MinimumLevel": {
          "Default": "Debug",
          "Override": {
            "Microsoft": "Warning"
          }
        },
        "WriteTo": [
          { "Name": "Console" },
          {
            "Name": "File",
            "Args": {
              "path": "logs/log.txt",
              "rollingInterval": "Day"
            }
          }
        ]
      },
      "SmtpSettings": {
        "Server": "in-v3.mailjet.com",
        "Port": 587,
        "Username": "42a3271857bc9ba1b9c0e72b43296311",
        "Password": "8f536fd40f664b94d0abaacea3bd52c7"
      },
      "Mailgun": {
        "ApiKey": "your-api-key",
        "Domain": "your-domain"
      },
      "Postmark": {
        "ApiKey": "2234b792-4397-4d87-bc7d-d47090d9d7e6"
      },
      "Logging": {
        "LogLevel": {
          "Default": "Information",
          "Microsoft.AspNetCore": "Warning"
        }
      },
      "HubApiClientOptions": {
        "BaseApiAddress": "http://hubapi:5002/",
        "Endpoint": "hubapi/"

        # //"BaseApiAddress": "http://192.168.10.42:5002/", docker
        # "BaseApiAddress": "http://192.168.10.42:8003/", //hosted
        # "Endpoint": "hubapi/"
      },
      "SagaApiClientOptions": {
        "BaseApiAddress": "http://sagamachine:5007/",
        "Endpoint": "Saga"

        # //"BaseApiAddress": "http://192.168.10.42:5007/", docker
        # "BaseApiAddress": "http://192.168.10.42:8004/", //hosted
        # "Endpoint": "Saga"
      },
      "LeaderBoardApiClientOptions": {
        "BaseApiAddress": "http://leaderboardapi:5004/",
        "Endpoint": "api/v1/Leaderboard/"

        # //"BaseApiAddress": "http://192.168.10.42:5004/", docker
        # "BaseApiAddress": "http://192.168.10.42:8002/", //hosted
        # "Endpoint": "api/v1/Leaderboard/"
      },
      "AllowedHosts": "*"
    }
kind: ConfigMap
metadata:
  annotations:
    use-subpath: "true"
  labels:
    io.kompose.service: adminapi
  name: adminapi-cm0
  namespace: onaimhub
