apiVersion: v1
kind: Service
metadata:
  name: testapi
  namespace: onaimhub
spec:
  ports:
    - name: "5005"
      port: 5005
      targetPort: 8080
  selector:
    app: testapi
  type: ClusterIP



